import 'package:flutter/material.dart' hide Badge;
import 'badge.dart';

/// All available badges in the app
class BadgeDefinitions {
  static const List<Badge> allBadges = [
    // ============ STREAK BADGES ============
    Badge(
      id: 'streak_3',
      name: 'Эхлэл',
      description: '3 хоног дараалан дасгал хийсэн',
      iconData: Icons.local_fire_department_rounded,
      category: BadgeCategory.streak,
      rarity: BadgeRarity.common,
      color: Colors.orange,
      requiredValue: 3,
      unit: 'хоног',
      xpReward: 50,
    ),
    Badge(
      id: 'streak_7',
      name: 'Долоо хоног',
      description: '7 хоног дараалан дасгал хийсэн',
      iconData: Icons.local_fire_department_rounded,
      category: BadgeCategory.streak,
      rarity: BadgeRarity.common,
      color: Colors.orange,
      requiredValue: 7,
      unit: 'хоног',
      xpReward: 100,
    ),
    Badge(
      id: 'streak_14',
      name: 'Хоёр долоо хоног',
      description: '14 хоног дараалан дасгал хийсэн',
      iconData: Icons.local_fire_department_rounded,
      category: BadgeCategory.streak,
      rarity: BadgeRarity.uncommon,
      color: Colors.orange,
      requiredValue: 14,
      unit: 'хоног',
      xpReward: 200,
    ),
    Badge(
      id: 'streak_30',
      name: 'Нэг сар',
      description: '30 хоног дараалан дасгал хийсэн',
      iconData: Icons.whatshot_rounded,
      category: BadgeCategory.streak,
      rarity: BadgeRarity.rare,
      color: Colors.deepOrange,
      requiredValue: 30,
      unit: 'хоног',
      xpReward: 500,
    ),
    Badge(
      id: 'streak_60',
      name: 'Хоёр сар',
      description: '60 хоног дараалан дасгал хийсэн',
      iconData: Icons.whatshot_rounded,
      category: BadgeCategory.streak,
      rarity: BadgeRarity.rare,
      color: Colors.deepOrange,
      requiredValue: 60,
      unit: 'хоног',
      xpReward: 800,
    ),
    Badge(
      id: 'streak_100',
      name: 'Зуун клуб',
      description: '100 хоног дараалан дасгал хийсэн',
      iconData: Icons.military_tech_rounded,
      category: BadgeCategory.streak,
      rarity: BadgeRarity.epic,
      color: Colors.amber,
      requiredValue: 100,
      unit: 'хоног',
      xpReward: 1500,
    ),
    Badge(
      id: 'streak_365',
      name: 'Жилийн аварга',
      description: '365 хоног дараалан дасгал хийсэн',
      iconData: Icons.emoji_events_rounded,
      category: BadgeCategory.streak,
      rarity: BadgeRarity.legendary,
      color: Colors.amber,
      requiredValue: 365,
      unit: 'хоног',
      xpReward: 5000,
    ),

    // ============ WORKOUT BADGES ============
    Badge(
      id: 'workout_1',
      name: 'Эхний алхам',
      description: 'Анхны дасгалаа хийсэн',
      iconData: Icons.fitness_center_rounded,
      category: BadgeCategory.workout,
      rarity: BadgeRarity.common,
      color: Colors.blue,
      requiredValue: 1,
      unit: 'дасгал',
      xpReward: 25,
    ),
    Badge(
      id: 'workout_10',
      name: 'Тогтвортой',
      description: '10 дасгал хийсэн',
      iconData: Icons.fitness_center_rounded,
      category: BadgeCategory.workout,
      rarity: BadgeRarity.common,
      color: Colors.blue,
      requiredValue: 10,
      unit: 'дасгал',
      xpReward: 100,
    ),
    Badge(
      id: 'workout_25',
      name: 'Дадлагажигч',
      description: '25 дасгал хийсэн',
      iconData: Icons.fitness_center_rounded,
      category: BadgeCategory.workout,
      rarity: BadgeRarity.uncommon,
      color: Colors.blue,
      requiredValue: 25,
      unit: 'дасгал',
      xpReward: 200,
    ),
    Badge(
      id: 'workout_50',
      name: 'Тамирчин',
      description: '50 дасгал хийсэн',
      iconData: Icons.sports_gymnastics_rounded,
      category: BadgeCategory.workout,
      rarity: BadgeRarity.uncommon,
      color: Colors.indigo,
      requiredValue: 50,
      unit: 'дасгал',
      xpReward: 400,
    ),
    Badge(
      id: 'workout_100',
      name: 'Зуутын гишүүн',
      description: '100 дасгал хийсэн',
      iconData: Icons.sports_gymnastics_rounded,
      category: BadgeCategory.workout,
      rarity: BadgeRarity.rare,
      color: Colors.indigo,
      requiredValue: 100,
      unit: 'дасгал',
      xpReward: 800,
    ),
    Badge(
      id: 'workout_250',
      name: 'Мэргэжилтэн',
      description: '250 дасгал хийсэн',
      iconData: Icons.workspace_premium_rounded,
      category: BadgeCategory.workout,
      rarity: BadgeRarity.epic,
      color: Colors.purple,
      requiredValue: 250,
      unit: 'дасгал',
      xpReward: 1500,
    ),
    Badge(
      id: 'workout_500',
      name: 'Домогт тамирчин',
      description: '500 дасгал хийсэн',
      iconData: Icons.workspace_premium_rounded,
      category: BadgeCategory.workout,
      rarity: BadgeRarity.legendary,
      color: Colors.purple,
      requiredValue: 500,
      unit: 'дасгал',
      xpReward: 3000,
    ),

    // ============ CHALLENGE BADGES ============
    Badge(
      id: 'challenge_1',
      name: 'Сорилцогч',
      description: 'Анхны сорилтоо дуусгасан',
      iconData: Icons.flag_rounded,
      category: BadgeCategory.challenge,
      rarity: BadgeRarity.common,
      color: Colors.teal,
      requiredValue: 1,
      unit: 'сорилт',
      xpReward: 100,
    ),
    Badge(
      id: 'challenge_5',
      name: 'Тууштай',
      description: '5 сорилт дуусгасан',
      iconData: Icons.flag_rounded,
      category: BadgeCategory.challenge,
      rarity: BadgeRarity.uncommon,
      color: Colors.teal,
      requiredValue: 5,
      unit: 'сорилт',
      xpReward: 400,
    ),
    Badge(
      id: 'challenge_10',
      name: 'Аварга сорилцогч',
      description: '10 сорилт дуусгасан',
      iconData: Icons.emoji_events_rounded,
      category: BadgeCategory.challenge,
      rarity: BadgeRarity.rare,
      color: Colors.teal,
      requiredValue: 10,
      unit: 'сорилт',
      xpReward: 800,
    ),
    Badge(
      id: 'challenge_25',
      name: 'Сорилтын мастер',
      description: '25 сорилт дуусгасан',
      iconData: Icons.military_tech_rounded,
      category: BadgeCategory.challenge,
      rarity: BadgeRarity.epic,
      color: Colors.cyan,
      requiredValue: 25,
      unit: 'сорилт',
      xpReward: 2000,
    ),

    // ============ WATER BADGES ============
    Badge(
      id: 'water_1',
      name: 'Усны анхны алхам',
      description: 'Өдрийн зорилгоо биелүүлсэн',
      iconData: Icons.water_drop_rounded,
      category: BadgeCategory.water,
      rarity: BadgeRarity.common,
      color: Colors.lightBlue,
      requiredValue: 1,
      unit: 'өдөр',
      xpReward: 25,
    ),
    Badge(
      id: 'water_7',
      name: 'Усны долоо хоног',
      description: '7 хоног дараалан усны зорилгоо биелүүлсэн',
      iconData: Icons.water_drop_rounded,
      category: BadgeCategory.water,
      rarity: BadgeRarity.uncommon,
      color: Colors.lightBlue,
      requiredValue: 7,
      unit: 'хоног',
      xpReward: 150,
    ),
    Badge(
      id: 'water_30',
      name: 'Усны сар',
      description: '30 хоног дараалан усны зорилгоо биелүүлсэн',
      iconData: Icons.waves_rounded,
      category: BadgeCategory.water,
      rarity: BadgeRarity.rare,
      color: Colors.blue,
      requiredValue: 30,
      unit: 'хоног',
      xpReward: 500,
    ),
    Badge(
      id: 'water_100',
      name: 'Усны мастер',
      description: '100 хоног усны зорилгоо биелүүлсэн',
      iconData: Icons.pool_rounded,
      category: BadgeCategory.water,
      rarity: BadgeRarity.epic,
      color: Colors.blue,
      requiredValue: 100,
      unit: 'хоног',
      xpReward: 1200,
    ),

    // ============ MILESTONE BADGES ============
    Badge(
      id: 'early_bird',
      name: 'Эрт босогч',
      description: 'Өглөөний 6 цагаас өмнө дасгал хийсэн',
      iconData: Icons.wb_sunny_rounded,
      category: BadgeCategory.milestone,
      rarity: BadgeRarity.uncommon,
      color: Colors.amber,
      requiredValue: 1,
      unit: 'удаа',
      xpReward: 100,
    ),
    Badge(
      id: 'night_owl',
      name: 'Шөнийн шувуу',
      description: 'Оройн 10 цагаас хойш дасгал хийсэн',
      iconData: Icons.nightlight_rounded,
      category: BadgeCategory.milestone,
      rarity: BadgeRarity.uncommon,
      color: Colors.indigo,
      requiredValue: 1,
      unit: 'удаа',
      xpReward: 100,
    ),
    Badge(
      id: 'weekend_warrior',
      name: 'Амралтын өдрийн дайчин',
      description: 'Амралтын өдрүүдэд дараалан дасгал хийсэн',
      iconData: Icons.weekend_rounded,
      category: BadgeCategory.milestone,
      rarity: BadgeRarity.uncommon,
      color: Colors.green,
      requiredValue: 4,
      unit: 'амралтын өдөр',
      xpReward: 200,
    ),
    Badge(
      id: 'perfect_week',
      name: 'Төгс долоо хоног',
      description: 'Долоо хоногийн бүх өдөр дасгал хийсэн',
      iconData: Icons.star_rounded,
      category: BadgeCategory.milestone,
      rarity: BadgeRarity.rare,
      color: Colors.amber,
      requiredValue: 7,
      unit: 'хоног',
      xpReward: 300,
    ),
    Badge(
      id: 'comeback_kid',
      name: 'Буцаж ирэгч',
      description: '7+ хоногийн завсарлагааны дараа дахин эхэлсэн',
      iconData: Icons.replay_rounded,
      category: BadgeCategory.milestone,
      rarity: BadgeRarity.uncommon,
      color: Colors.green,
      requiredValue: 1,
      unit: 'удаа',
      xpReward: 150,
    ),

    // ============ SOCIAL BADGES ============
    Badge(
      id: 'social_share',
      name: 'Хуваалцагч',
      description: 'Анхны үр дүнгээ хуваалцсан',
      iconData: Icons.share_rounded,
      category: BadgeCategory.social,
      rarity: BadgeRarity.common,
      color: Colors.pink,
      requiredValue: 1,
      unit: 'удаа',
      xpReward: 50,
    ),
    Badge(
      id: 'friend_inviter',
      name: 'Найз урьсан',
      description: 'Найзаа аппд урьсан',
      iconData: Icons.person_add_rounded,
      category: BadgeCategory.social,
      rarity: BadgeRarity.uncommon,
      color: Colors.pink,
      requiredValue: 1,
      unit: 'найз',
      xpReward: 200,
    ),
    Badge(
      id: 'team_player',
      name: 'Багийн тоглогч',
      description: 'Бүлгийн сорилтод оролцсон',
      iconData: Icons.groups_rounded,
      category: BadgeCategory.social,
      rarity: BadgeRarity.uncommon,
      color: Colors.deepPurple,
      requiredValue: 1,
      unit: 'сорилт',
      xpReward: 150,
    ),

    // ============ SEASONAL BADGES ============
    Badge(
      id: 'new_year_2024',
      name: 'Шинэ жилийн шийдвэр 2024',
      description: '2024 оны 1-р сарын 1-нд дасгал хийсэн',
      iconData: Icons.celebration_rounded,
      category: BadgeCategory.seasonal,
      rarity: BadgeRarity.rare,
      color: Colors.red,
      requiredValue: 1,
      unit: 'удаа',
      xpReward: 500,
      isSecret: true,
    ),
    Badge(
      id: 'summer_warrior',
      name: 'Зуны дайчин',
      description: 'Зуны улиралд 30+ дасгал хийсэн',
      iconData: Icons.wb_sunny_rounded,
      category: BadgeCategory.seasonal,
      rarity: BadgeRarity.rare,
      color: Colors.orange,
      requiredValue: 30,
      unit: 'дасгал',
      xpReward: 600,
    ),
  ];

  /// Get badge by ID
  static Badge? getBadgeById(String id) {
    try {
      return allBadges.firstWhere((b) => b.id == id);
    } catch (_) {
      return null;
    }
  }

  /// Get badges by category
  static List<Badge> getBadgesByCategory(BadgeCategory category) {
    return allBadges.where((b) => b.category == category).toList();
  }

  /// Get badges by rarity
  static List<Badge> getBadgesByRarity(BadgeRarity rarity) {
    return allBadges.where((b) => b.rarity == rarity).toList();
  }

  /// Get non-secret badges
  static List<Badge> get visibleBadges {
    return allBadges.where((b) => !b.isSecret).toList();
  }
}
